source 'https://github.com/CocoaPods/Specs.git'

target 'JCSegmentBarController', :exclusive => true do
  pod "JCSegmentBarController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "JCSegmentBarController", :path => "../"

  
end
